"""changed user table

Revision ID: 00ea57135dce
Revises: bf43989695ec
Create Date: 2018-11-03 15:16:53.637621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea57135dce'
down_revision = 'bf43989695ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_fb_id'), 'user', ['fb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fb_id'), table_name='user')
    op.drop_column('user', 'fb_id')
    # ### end Alembic commands ###
