"""preliminary tables

Revision ID: bf43989695ec
Revises: 
Create Date: 2018-11-03 15:06:14.025001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf43989695ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention',
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('intervention_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mid_conversation', sa.Boolean(), nullable=True),
    sa.Column('has_onboarded', sa.Boolean(), nullable=True),
    sa.Column('last_action', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_has_onboarded'), 'user', ['has_onboarded'], unique=False)
    op.create_index(op.f('ix_user_last_action'), 'user', ['last_action'], unique=False)
    op.create_index(op.f('ix_user_mid_conversation'), 'user', ['mid_conversation'], unique=False)
    op.create_table('checkin',
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('baseline', sa.Integer(), nullable=True),
    sa.Column('tried_intervention', sa.Boolean(), nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.intervention_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('checkin_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_checkin_baseline'), 'checkin', ['baseline'], unique=False)
    op.create_index(op.f('ix_checkin_datetime'), 'checkin', ['datetime'], unique=False)
    op.create_index(op.f('ix_checkin_impact'), 'checkin', ['impact'], unique=False)
    op.create_index(op.f('ix_checkin_tried_intervention'), 'checkin', ['tried_intervention'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_tried_intervention'), table_name='checkin')
    op.drop_index(op.f('ix_checkin_impact'), table_name='checkin')
    op.drop_index(op.f('ix_checkin_datetime'), table_name='checkin')
    op.drop_index(op.f('ix_checkin_baseline'), table_name='checkin')
    op.drop_table('checkin')
    op.drop_index(op.f('ix_user_mid_conversation'), table_name='user')
    op.drop_index(op.f('ix_user_last_action'), table_name='user')
    op.drop_index(op.f('ix_user_has_onboarded'), table_name='user')
    op.drop_table('user')
    op.drop_table('intervention')
    # ### end Alembic commands ###
