"""Message table

Revision ID: c3d933b01114
Revises: c0bf9bc13378
Create Date: 2018-11-03 19:34:08.834826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d933b01114'
down_revision = 'c0bf9bc13378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Message_datetime'), 'Message', ['datetime'], unique=False)
    op.create_index(op.f('ix_Message_text'), 'Message', ['text'], unique=False)
    op.drop_index('ix_last_message_datetime', table_name='last_message')
    op.drop_index('ix_last_message_fb_id', table_name='last_message')
    op.drop_table('last_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_message',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('fb_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_index('ix_last_message_fb_id', 'last_message', ['fb_id'], unique=1)
    op.create_index('ix_last_message_datetime', 'last_message', ['datetime'], unique=False)
    op.drop_index(op.f('ix_Message_text'), table_name='Message')
    op.drop_index(op.f('ix_Message_datetime'), table_name='Message')
    op.drop_table('Message')
    # ### end Alembic commands ###
